#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SumUpApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="ASPNETDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChungKhoan(ChungKhoan instance);
    partial void UpdateChungKhoan(ChungKhoan instance);
    partial void DeleteChungKhoan(ChungKhoan instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ASPNETDBConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChungKhoan> ChungKhoans
		{
			get
			{
				return this.GetTable<ChungKhoan>();
			}
		}
	}
	
	[Table(Name="dbo.ChungKhoan")]
	public partial class ChungKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaChungKhoan;
		
		private System.Nullable<double> _GiaTran;
		
		private System.Nullable<double> _GiaSan;
		
		private System.Nullable<double> _GiaThamChieu;
		
		private System.Nullable<double> _TKLMua;
		
		private System.Nullable<double> _KL3Mua;
		
		private System.Nullable<double> _Gia3Mua;
		
		private System.Nullable<double> _KL2Mua;
		
		private System.Nullable<double> _Gia2Mua;
		
		private System.Nullable<double> _KL1Mua;
		
		private System.Nullable<double> _Gia1Mua;
		
		private System.Nullable<double> _GiaKhopLenhGanNhat;
		
		private System.Nullable<double> _KLKhopLenhGanNhat;
		
		private System.Nullable<double> _TKLKhopLenhHienTai;
		
		private System.Nullable<double> _ChenhLechGiaKhopLenh;
		
		private System.Nullable<double> _TKLBan;
		
		private System.Nullable<double> _KL3Ban;
		
		private System.Nullable<double> _Gia3Ban;
		
		private System.Nullable<double> _KL2Ban;
		
		private System.Nullable<double> _Gia2Ban;
		
		private System.Nullable<double> _KL1Ban;
		
		private System.Nullable<double> _Gia1Ban;
		
		private System.Nullable<double> _GiaKhopTrungBinh;
		
		private System.Nullable<double> _GiaKhopCaoNhat;
		
		private System.Nullable<double> _GiaKhopThapNhat;
		
		private System.Nullable<double> _GiaPhien1;
		
		private System.Nullable<double> _KhoiLuongPhien1;
		
		private System.Nullable<double> _GiaKhopTrungBinhPhien2;
		
		private System.Nullable<double> _GiaKhopCaoNhatPhien2;
		
		private System.Nullable<double> _GiakhopThapNhatPhien2;
		
		private System.Nullable<double> _TKLKhopPhien2;
		
		private System.Nullable<double> _KLMuaNuocNgoai;
		
		private System.Nullable<double> _KLBanNuocNgoai;
		
		private System.Nullable<double> _KLConLaiNuocNgoai;
		
		private System.Nullable<System.DateTime> _NgayGiaoDich;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChungKhoanChanging(string value);
    partial void OnMaChungKhoanChanged();
    partial void OnGiaTranChanging(System.Nullable<double> value);
    partial void OnGiaTranChanged();
    partial void OnGiaSanChanging(System.Nullable<double> value);
    partial void OnGiaSanChanged();
    partial void OnGiaThamChieuChanging(System.Nullable<double> value);
    partial void OnGiaThamChieuChanged();
    partial void OnTKLMuaChanging(System.Nullable<double> value);
    partial void OnTKLMuaChanged();
    partial void OnKL3MuaChanging(System.Nullable<double> value);
    partial void OnKL3MuaChanged();
    partial void OnGia3MuaChanging(System.Nullable<double> value);
    partial void OnGia3MuaChanged();
    partial void OnKL2MuaChanging(System.Nullable<double> value);
    partial void OnKL2MuaChanged();
    partial void OnGia2MuaChanging(System.Nullable<double> value);
    partial void OnGia2MuaChanged();
    partial void OnKL1MuaChanging(System.Nullable<double> value);
    partial void OnKL1MuaChanged();
    partial void OnGia1MuaChanging(System.Nullable<double> value);
    partial void OnGia1MuaChanged();
    partial void OnGiaKhopLenhGanNhatChanging(System.Nullable<double> value);
    partial void OnGiaKhopLenhGanNhatChanged();
    partial void OnKLKhopLenhGanNhatChanging(System.Nullable<double> value);
    partial void OnKLKhopLenhGanNhatChanged();
    partial void OnTKLKhopLenhHienTaiChanging(System.Nullable<double> value);
    partial void OnTKLKhopLenhHienTaiChanged();
    partial void OnChenhLechGiaKhopLenhChanging(System.Nullable<double> value);
    partial void OnChenhLechGiaKhopLenhChanged();
    partial void OnTKLBanChanging(System.Nullable<double> value);
    partial void OnTKLBanChanged();
    partial void OnKL3BanChanging(System.Nullable<double> value);
    partial void OnKL3BanChanged();
    partial void OnGia3BanChanging(System.Nullable<double> value);
    partial void OnGia3BanChanged();
    partial void OnKL2BanChanging(System.Nullable<double> value);
    partial void OnKL2BanChanged();
    partial void OnGia2BanChanging(System.Nullable<double> value);
    partial void OnGia2BanChanged();
    partial void OnKL1BanChanging(System.Nullable<double> value);
    partial void OnKL1BanChanged();
    partial void OnGia1BanChanging(System.Nullable<double> value);
    partial void OnGia1BanChanged();
    partial void OnGiaKhopTrungBinhChanging(System.Nullable<double> value);
    partial void OnGiaKhopTrungBinhChanged();
    partial void OnGiaKhopCaoNhatChanging(System.Nullable<double> value);
    partial void OnGiaKhopCaoNhatChanged();
    partial void OnGiaKhopThapNhatChanging(System.Nullable<double> value);
    partial void OnGiaKhopThapNhatChanged();
    partial void OnGiaPhien1Changing(System.Nullable<double> value);
    partial void OnGiaPhien1Changed();
    partial void OnKhoiLuongPhien1Changing(System.Nullable<double> value);
    partial void OnKhoiLuongPhien1Changed();
    partial void OnGiaKhopTrungBinhPhien2Changing(System.Nullable<double> value);
    partial void OnGiaKhopTrungBinhPhien2Changed();
    partial void OnGiaKhopCaoNhatPhien2Changing(System.Nullable<double> value);
    partial void OnGiaKhopCaoNhatPhien2Changed();
    partial void OnGiakhopThapNhatPhien2Changing(System.Nullable<double> value);
    partial void OnGiakhopThapNhatPhien2Changed();
    partial void OnTKLKhopPhien2Changing(System.Nullable<double> value);
    partial void OnTKLKhopPhien2Changed();
    partial void OnKLMuaNuocNgoaiChanging(System.Nullable<double> value);
    partial void OnKLMuaNuocNgoaiChanged();
    partial void OnKLBanNuocNgoaiChanging(System.Nullable<double> value);
    partial void OnKLBanNuocNgoaiChanged();
    partial void OnKLConLaiNuocNgoaiChanging(System.Nullable<double> value);
    partial void OnKLConLaiNuocNgoaiChanged();
    partial void OnNgayGiaoDichChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayGiaoDichChanged();
    #endregion
		
		public ChungKhoan()
		{
			OnCreated();
		}
		
		[Column(Storage="_MaChungKhoan", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaChungKhoan
		{
			get
			{
				return this._MaChungKhoan;
			}
			set
			{
				if ((this._MaChungKhoan != value))
				{
					this.OnMaChungKhoanChanging(value);
					this.SendPropertyChanging();
					this._MaChungKhoan = value;
					this.SendPropertyChanged("MaChungKhoan");
					this.OnMaChungKhoanChanged();
				}
			}
		}
		
		[Column(Storage="_GiaTran", DbType="Float")]
		public System.Nullable<double> GiaTran
		{
			get
			{
				return this._GiaTran;
			}
			set
			{
				if ((this._GiaTran != value))
				{
					this.OnGiaTranChanging(value);
					this.SendPropertyChanging();
					this._GiaTran = value;
					this.SendPropertyChanged("GiaTran");
					this.OnGiaTranChanged();
				}
			}
		}
		
		[Column(Storage="_GiaSan", DbType="Float")]
		public System.Nullable<double> GiaSan
		{
			get
			{
				return this._GiaSan;
			}
			set
			{
				if ((this._GiaSan != value))
				{
					this.OnGiaSanChanging(value);
					this.SendPropertyChanging();
					this._GiaSan = value;
					this.SendPropertyChanged("GiaSan");
					this.OnGiaSanChanged();
				}
			}
		}
		
		[Column(Storage="_GiaThamChieu", DbType="Float")]
		public System.Nullable<double> GiaThamChieu
		{
			get
			{
				return this._GiaThamChieu;
			}
			set
			{
				if ((this._GiaThamChieu != value))
				{
					this.OnGiaThamChieuChanging(value);
					this.SendPropertyChanging();
					this._GiaThamChieu = value;
					this.SendPropertyChanged("GiaThamChieu");
					this.OnGiaThamChieuChanged();
				}
			}
		}
		
		[Column(Storage="_TKLMua", DbType="Float")]
		public System.Nullable<double> TKLMua
		{
			get
			{
				return this._TKLMua;
			}
			set
			{
				if ((this._TKLMua != value))
				{
					this.OnTKLMuaChanging(value);
					this.SendPropertyChanging();
					this._TKLMua = value;
					this.SendPropertyChanged("TKLMua");
					this.OnTKLMuaChanged();
				}
			}
		}
		
		[Column(Storage="_KL3Mua", DbType="Float")]
		public System.Nullable<double> KL3Mua
		{
			get
			{
				return this._KL3Mua;
			}
			set
			{
				if ((this._KL3Mua != value))
				{
					this.OnKL3MuaChanging(value);
					this.SendPropertyChanging();
					this._KL3Mua = value;
					this.SendPropertyChanged("KL3Mua");
					this.OnKL3MuaChanged();
				}
			}
		}
		
		[Column(Storage="_Gia3Mua", DbType="Float")]
		public System.Nullable<double> Gia3Mua
		{
			get
			{
				return this._Gia3Mua;
			}
			set
			{
				if ((this._Gia3Mua != value))
				{
					this.OnGia3MuaChanging(value);
					this.SendPropertyChanging();
					this._Gia3Mua = value;
					this.SendPropertyChanged("Gia3Mua");
					this.OnGia3MuaChanged();
				}
			}
		}
		
		[Column(Storage="_KL2Mua", DbType="Float")]
		public System.Nullable<double> KL2Mua
		{
			get
			{
				return this._KL2Mua;
			}
			set
			{
				if ((this._KL2Mua != value))
				{
					this.OnKL2MuaChanging(value);
					this.SendPropertyChanging();
					this._KL2Mua = value;
					this.SendPropertyChanged("KL2Mua");
					this.OnKL2MuaChanged();
				}
			}
		}
		
		[Column(Storage="_Gia2Mua", DbType="Float")]
		public System.Nullable<double> Gia2Mua
		{
			get
			{
				return this._Gia2Mua;
			}
			set
			{
				if ((this._Gia2Mua != value))
				{
					this.OnGia2MuaChanging(value);
					this.SendPropertyChanging();
					this._Gia2Mua = value;
					this.SendPropertyChanged("Gia2Mua");
					this.OnGia2MuaChanged();
				}
			}
		}
		
		[Column(Storage="_KL1Mua", DbType="Float")]
		public System.Nullable<double> KL1Mua
		{
			get
			{
				return this._KL1Mua;
			}
			set
			{
				if ((this._KL1Mua != value))
				{
					this.OnKL1MuaChanging(value);
					this.SendPropertyChanging();
					this._KL1Mua = value;
					this.SendPropertyChanged("KL1Mua");
					this.OnKL1MuaChanged();
				}
			}
		}
		
		[Column(Storage="_Gia1Mua", DbType="Float")]
		public System.Nullable<double> Gia1Mua
		{
			get
			{
				return this._Gia1Mua;
			}
			set
			{
				if ((this._Gia1Mua != value))
				{
					this.OnGia1MuaChanging(value);
					this.SendPropertyChanging();
					this._Gia1Mua = value;
					this.SendPropertyChanged("Gia1Mua");
					this.OnGia1MuaChanged();
				}
			}
		}
		
		[Column(Storage="_GiaKhopLenhGanNhat", DbType="Float")]
		public System.Nullable<double> GiaKhopLenhGanNhat
		{
			get
			{
				return this._GiaKhopLenhGanNhat;
			}
			set
			{
				if ((this._GiaKhopLenhGanNhat != value))
				{
					this.OnGiaKhopLenhGanNhatChanging(value);
					this.SendPropertyChanging();
					this._GiaKhopLenhGanNhat = value;
					this.SendPropertyChanged("GiaKhopLenhGanNhat");
					this.OnGiaKhopLenhGanNhatChanged();
				}
			}
		}
		
		[Column(Storage="_KLKhopLenhGanNhat", DbType="Float")]
		public System.Nullable<double> KLKhopLenhGanNhat
		{
			get
			{
				return this._KLKhopLenhGanNhat;
			}
			set
			{
				if ((this._KLKhopLenhGanNhat != value))
				{
					this.OnKLKhopLenhGanNhatChanging(value);
					this.SendPropertyChanging();
					this._KLKhopLenhGanNhat = value;
					this.SendPropertyChanged("KLKhopLenhGanNhat");
					this.OnKLKhopLenhGanNhatChanged();
				}
			}
		}
		
		[Column(Storage="_TKLKhopLenhHienTai", DbType="Float")]
		public System.Nullable<double> TKLKhopLenhHienTai
		{
			get
			{
				return this._TKLKhopLenhHienTai;
			}
			set
			{
				if ((this._TKLKhopLenhHienTai != value))
				{
					this.OnTKLKhopLenhHienTaiChanging(value);
					this.SendPropertyChanging();
					this._TKLKhopLenhHienTai = value;
					this.SendPropertyChanged("TKLKhopLenhHienTai");
					this.OnTKLKhopLenhHienTaiChanged();
				}
			}
		}
		
		[Column(Storage="_ChenhLechGiaKhopLenh", DbType="Float")]
		public System.Nullable<double> ChenhLechGiaKhopLenh
		{
			get
			{
				return this._ChenhLechGiaKhopLenh;
			}
			set
			{
				if ((this._ChenhLechGiaKhopLenh != value))
				{
					this.OnChenhLechGiaKhopLenhChanging(value);
					this.SendPropertyChanging();
					this._ChenhLechGiaKhopLenh = value;
					this.SendPropertyChanged("ChenhLechGiaKhopLenh");
					this.OnChenhLechGiaKhopLenhChanged();
				}
			}
		}
		
		[Column(Storage="_TKLBan", DbType="Float")]
		public System.Nullable<double> TKLBan
		{
			get
			{
				return this._TKLBan;
			}
			set
			{
				if ((this._TKLBan != value))
				{
					this.OnTKLBanChanging(value);
					this.SendPropertyChanging();
					this._TKLBan = value;
					this.SendPropertyChanged("TKLBan");
					this.OnTKLBanChanged();
				}
			}
		}
		
		[Column(Storage="_KL3Ban", DbType="Float")]
		public System.Nullable<double> KL3Ban
		{
			get
			{
				return this._KL3Ban;
			}
			set
			{
				if ((this._KL3Ban != value))
				{
					this.OnKL3BanChanging(value);
					this.SendPropertyChanging();
					this._KL3Ban = value;
					this.SendPropertyChanged("KL3Ban");
					this.OnKL3BanChanged();
				}
			}
		}
		
		[Column(Storage="_Gia3Ban", DbType="Float")]
		public System.Nullable<double> Gia3Ban
		{
			get
			{
				return this._Gia3Ban;
			}
			set
			{
				if ((this._Gia3Ban != value))
				{
					this.OnGia3BanChanging(value);
					this.SendPropertyChanging();
					this._Gia3Ban = value;
					this.SendPropertyChanged("Gia3Ban");
					this.OnGia3BanChanged();
				}
			}
		}
		
		[Column(Storage="_KL2Ban", DbType="Float")]
		public System.Nullable<double> KL2Ban
		{
			get
			{
				return this._KL2Ban;
			}
			set
			{
				if ((this._KL2Ban != value))
				{
					this.OnKL2BanChanging(value);
					this.SendPropertyChanging();
					this._KL2Ban = value;
					this.SendPropertyChanged("KL2Ban");
					this.OnKL2BanChanged();
				}
			}
		}
		
		[Column(Storage="_Gia2Ban", DbType="Float")]
		public System.Nullable<double> Gia2Ban
		{
			get
			{
				return this._Gia2Ban;
			}
			set
			{
				if ((this._Gia2Ban != value))
				{
					this.OnGia2BanChanging(value);
					this.SendPropertyChanging();
					this._Gia2Ban = value;
					this.SendPropertyChanged("Gia2Ban");
					this.OnGia2BanChanged();
				}
			}
		}
		
		[Column(Storage="_KL1Ban", DbType="Float")]
		public System.Nullable<double> KL1Ban
		{
			get
			{
				return this._KL1Ban;
			}
			set
			{
				if ((this._KL1Ban != value))
				{
					this.OnKL1BanChanging(value);
					this.SendPropertyChanging();
					this._KL1Ban = value;
					this.SendPropertyChanged("KL1Ban");
					this.OnKL1BanChanged();
				}
			}
		}
		
		[Column(Storage="_Gia1Ban", DbType="Float")]
		public System.Nullable<double> Gia1Ban
		{
			get
			{
				return this._Gia1Ban;
			}
			set
			{
				if ((this._Gia1Ban != value))
				{
					this.OnGia1BanChanging(value);
					this.SendPropertyChanging();
					this._Gia1Ban = value;
					this.SendPropertyChanged("Gia1Ban");
					this.OnGia1BanChanged();
				}
			}
		}
		
		[Column(Storage="_GiaKhopTrungBinh", DbType="Float")]
		public System.Nullable<double> GiaKhopTrungBinh
		{
			get
			{
				return this._GiaKhopTrungBinh;
			}
			set
			{
				if ((this._GiaKhopTrungBinh != value))
				{
					this.OnGiaKhopTrungBinhChanging(value);
					this.SendPropertyChanging();
					this._GiaKhopTrungBinh = value;
					this.SendPropertyChanged("GiaKhopTrungBinh");
					this.OnGiaKhopTrungBinhChanged();
				}
			}
		}
		
		[Column(Storage="_GiaKhopCaoNhat", DbType="Float")]
		public System.Nullable<double> GiaKhopCaoNhat
		{
			get
			{
				return this._GiaKhopCaoNhat;
			}
			set
			{
				if ((this._GiaKhopCaoNhat != value))
				{
					this.OnGiaKhopCaoNhatChanging(value);
					this.SendPropertyChanging();
					this._GiaKhopCaoNhat = value;
					this.SendPropertyChanged("GiaKhopCaoNhat");
					this.OnGiaKhopCaoNhatChanged();
				}
			}
		}
		
		[Column(Storage="_GiaKhopThapNhat", DbType="Float")]
		public System.Nullable<double> GiaKhopThapNhat
		{
			get
			{
				return this._GiaKhopThapNhat;
			}
			set
			{
				if ((this._GiaKhopThapNhat != value))
				{
					this.OnGiaKhopThapNhatChanging(value);
					this.SendPropertyChanging();
					this._GiaKhopThapNhat = value;
					this.SendPropertyChanged("GiaKhopThapNhat");
					this.OnGiaKhopThapNhatChanged();
				}
			}
		}
		
		[Column(Storage="_GiaPhien1", DbType="Float")]
		public System.Nullable<double> GiaPhien1
		{
			get
			{
				return this._GiaPhien1;
			}
			set
			{
				if ((this._GiaPhien1 != value))
				{
					this.OnGiaPhien1Changing(value);
					this.SendPropertyChanging();
					this._GiaPhien1 = value;
					this.SendPropertyChanged("GiaPhien1");
					this.OnGiaPhien1Changed();
				}
			}
		}
		
		[Column(Storage="_KhoiLuongPhien1", DbType="Float")]
		public System.Nullable<double> KhoiLuongPhien1
		{
			get
			{
				return this._KhoiLuongPhien1;
			}
			set
			{
				if ((this._KhoiLuongPhien1 != value))
				{
					this.OnKhoiLuongPhien1Changing(value);
					this.SendPropertyChanging();
					this._KhoiLuongPhien1 = value;
					this.SendPropertyChanged("KhoiLuongPhien1");
					this.OnKhoiLuongPhien1Changed();
				}
			}
		}
		
		[Column(Storage="_GiaKhopTrungBinhPhien2", DbType="Float")]
		public System.Nullable<double> GiaKhopTrungBinhPhien2
		{
			get
			{
				return this._GiaKhopTrungBinhPhien2;
			}
			set
			{
				if ((this._GiaKhopTrungBinhPhien2 != value))
				{
					this.OnGiaKhopTrungBinhPhien2Changing(value);
					this.SendPropertyChanging();
					this._GiaKhopTrungBinhPhien2 = value;
					this.SendPropertyChanged("GiaKhopTrungBinhPhien2");
					this.OnGiaKhopTrungBinhPhien2Changed();
				}
			}
		}
		
		[Column(Storage="_GiaKhopCaoNhatPhien2", DbType="Float")]
		public System.Nullable<double> GiaKhopCaoNhatPhien2
		{
			get
			{
				return this._GiaKhopCaoNhatPhien2;
			}
			set
			{
				if ((this._GiaKhopCaoNhatPhien2 != value))
				{
					this.OnGiaKhopCaoNhatPhien2Changing(value);
					this.SendPropertyChanging();
					this._GiaKhopCaoNhatPhien2 = value;
					this.SendPropertyChanged("GiaKhopCaoNhatPhien2");
					this.OnGiaKhopCaoNhatPhien2Changed();
				}
			}
		}
		
		[Column(Storage="_GiakhopThapNhatPhien2", DbType="Float")]
		public System.Nullable<double> GiakhopThapNhatPhien2
		{
			get
			{
				return this._GiakhopThapNhatPhien2;
			}
			set
			{
				if ((this._GiakhopThapNhatPhien2 != value))
				{
					this.OnGiakhopThapNhatPhien2Changing(value);
					this.SendPropertyChanging();
					this._GiakhopThapNhatPhien2 = value;
					this.SendPropertyChanged("GiakhopThapNhatPhien2");
					this.OnGiakhopThapNhatPhien2Changed();
				}
			}
		}
		
		[Column(Storage="_TKLKhopPhien2", DbType="Float")]
		public System.Nullable<double> TKLKhopPhien2
		{
			get
			{
				return this._TKLKhopPhien2;
			}
			set
			{
				if ((this._TKLKhopPhien2 != value))
				{
					this.OnTKLKhopPhien2Changing(value);
					this.SendPropertyChanging();
					this._TKLKhopPhien2 = value;
					this.SendPropertyChanged("TKLKhopPhien2");
					this.OnTKLKhopPhien2Changed();
				}
			}
		}
		
		[Column(Storage="_KLMuaNuocNgoai", DbType="Float")]
		public System.Nullable<double> KLMuaNuocNgoai
		{
			get
			{
				return this._KLMuaNuocNgoai;
			}
			set
			{
				if ((this._KLMuaNuocNgoai != value))
				{
					this.OnKLMuaNuocNgoaiChanging(value);
					this.SendPropertyChanging();
					this._KLMuaNuocNgoai = value;
					this.SendPropertyChanged("KLMuaNuocNgoai");
					this.OnKLMuaNuocNgoaiChanged();
				}
			}
		}
		
		[Column(Storage="_KLBanNuocNgoai", DbType="Float")]
		public System.Nullable<double> KLBanNuocNgoai
		{
			get
			{
				return this._KLBanNuocNgoai;
			}
			set
			{
				if ((this._KLBanNuocNgoai != value))
				{
					this.OnKLBanNuocNgoaiChanging(value);
					this.SendPropertyChanging();
					this._KLBanNuocNgoai = value;
					this.SendPropertyChanged("KLBanNuocNgoai");
					this.OnKLBanNuocNgoaiChanged();
				}
			}
		}
		
		[Column(Storage="_KLConLaiNuocNgoai", DbType="Float")]
		public System.Nullable<double> KLConLaiNuocNgoai
		{
			get
			{
				return this._KLConLaiNuocNgoai;
			}
			set
			{
				if ((this._KLConLaiNuocNgoai != value))
				{
					this.OnKLConLaiNuocNgoaiChanging(value);
					this.SendPropertyChanging();
					this._KLConLaiNuocNgoai = value;
					this.SendPropertyChanged("KLConLaiNuocNgoai");
					this.OnKLConLaiNuocNgoaiChanged();
				}
			}
		}
		
		[Column(Storage="_NgayGiaoDich", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayGiaoDich
		{
			get
			{
				return this._NgayGiaoDich;
			}
			set
			{
				if ((this._NgayGiaoDich != value))
				{
					this.OnNgayGiaoDichChanging(value);
					this.SendPropertyChanging();
					this._NgayGiaoDich = value;
					this.SendPropertyChanged("NgayGiaoDich");
					this.OnNgayGiaoDichChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
