//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace CaroSocialNetwork.CaroWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CaroWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CaroWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoomListOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateRoomOperationCompleted;
        
        private System.Threading.SendOrPostCallback JoinRoomOperationCompleted;
        
        private System.Threading.SendOrPostCallback LeaveRoomOperationCompleted;
        
        private System.Threading.SendOrPostCallback MoveOperationCompleted;
        
        private System.Threading.SendOrPostCallback WaitingForOpponentOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckGameOverOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CaroWebService() {
            this.Url = global::CaroSocialNetwork.Properties.Settings.Default.CaroSocialNetwork_CaroWebService_CaroWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetRoomListCompletedEventHandler GetRoomListCompleted;
        
        /// <remarks/>
        public event CreateRoomCompletedEventHandler CreateRoomCompleted;
        
        /// <remarks/>
        public event JoinRoomCompletedEventHandler JoinRoomCompleted;
        
        /// <remarks/>
        public event LeaveRoomCompletedEventHandler LeaveRoomCompleted;
        
        /// <remarks/>
        public event MoveCompletedEventHandler MoveCompleted;
        
        /// <remarks/>
        public event WaitingForOpponentCompletedEventHandler WaitingForOpponentCompleted;
        
        /// <remarks/>
        public event CheckGameOverCompletedEventHandler CheckGameOverCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetRoomList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Room[] GetRoomList() {
            object[] results = this.Invoke("GetRoomList", new object[0]);
            return ((Room[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRoomListAsync() {
            this.GetRoomListAsync(null);
        }
        
        /// <remarks/>
        public void GetRoomListAsync(object userState) {
            if ((this.GetRoomListOperationCompleted == null)) {
                this.GetRoomListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoomListOperationCompleted);
            }
            this.InvokeAsync("GetRoomList", new object[0], this.GetRoomListOperationCompleted, userState);
        }
        
        private void OnGetRoomListOperationCompleted(object arg) {
            if ((this.GetRoomListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoomListCompleted(this, new GetRoomListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateRoom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateRoom(string username, bool playwithmachine, out int roomIndex) {
            object[] results = this.Invoke("CreateRoom", new object[] {
                        username,
                        playwithmachine});
            roomIndex = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateRoomAsync(string username, bool playwithmachine) {
            this.CreateRoomAsync(username, playwithmachine, null);
        }
        
        /// <remarks/>
        public void CreateRoomAsync(string username, bool playwithmachine, object userState) {
            if ((this.CreateRoomOperationCompleted == null)) {
                this.CreateRoomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateRoomOperationCompleted);
            }
            this.InvokeAsync("CreateRoom", new object[] {
                        username,
                        playwithmachine}, this.CreateRoomOperationCompleted, userState);
        }
        
        private void OnCreateRoomOperationCompleted(object arg) {
            if ((this.CreateRoomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateRoomCompleted(this, new CreateRoomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/JoinRoom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool JoinRoom(int roomid, string username) {
            object[] results = this.Invoke("JoinRoom", new object[] {
                        roomid,
                        username});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void JoinRoomAsync(int roomid, string username) {
            this.JoinRoomAsync(roomid, username, null);
        }
        
        /// <remarks/>
        public void JoinRoomAsync(int roomid, string username, object userState) {
            if ((this.JoinRoomOperationCompleted == null)) {
                this.JoinRoomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJoinRoomOperationCompleted);
            }
            this.InvokeAsync("JoinRoom", new object[] {
                        roomid,
                        username}, this.JoinRoomOperationCompleted, userState);
        }
        
        private void OnJoinRoomOperationCompleted(object arg) {
            if ((this.JoinRoomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JoinRoomCompleted(this, new JoinRoomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LeaveRoom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LeaveRoom(ref int roomid, string username) {
            object[] results = this.Invoke("LeaveRoom", new object[] {
                        roomid,
                        username});
            roomid = ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LeaveRoomAsync(int roomid, string username) {
            this.LeaveRoomAsync(roomid, username, null);
        }
        
        /// <remarks/>
        public void LeaveRoomAsync(int roomid, string username, object userState) {
            if ((this.LeaveRoomOperationCompleted == null)) {
                this.LeaveRoomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLeaveRoomOperationCompleted);
            }
            this.InvokeAsync("LeaveRoom", new object[] {
                        roomid,
                        username}, this.LeaveRoomOperationCompleted, userState);
        }
        
        private void OnLeaveRoomOperationCompleted(object arg) {
            if ((this.LeaveRoomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LeaveRoomCompleted(this, new LeaveRoomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Move", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Move(int roomid, string username, int userX, int userY) {
            this.Invoke("Move", new object[] {
                        roomid,
                        username,
                        userX,
                        userY});
        }
        
        /// <remarks/>
        public void MoveAsync(int roomid, string username, int userX, int userY) {
            this.MoveAsync(roomid, username, userX, userY, null);
        }
        
        /// <remarks/>
        public void MoveAsync(int roomid, string username, int userX, int userY, object userState) {
            if ((this.MoveOperationCompleted == null)) {
                this.MoveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMoveOperationCompleted);
            }
            this.InvokeAsync("Move", new object[] {
                        roomid,
                        username,
                        userX,
                        userY}, this.MoveOperationCompleted, userState);
        }
        
        private void OnMoveOperationCompleted(object arg) {
            if ((this.MoveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MoveCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WaitingForOpponent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] WaitingForOpponent(int roomid, string username) {
            object[] results = this.Invoke("WaitingForOpponent", new object[] {
                        roomid,
                        username});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void WaitingForOpponentAsync(int roomid, string username) {
            this.WaitingForOpponentAsync(roomid, username, null);
        }
        
        /// <remarks/>
        public void WaitingForOpponentAsync(int roomid, string username, object userState) {
            if ((this.WaitingForOpponentOperationCompleted == null)) {
                this.WaitingForOpponentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWaitingForOpponentOperationCompleted);
            }
            this.InvokeAsync("WaitingForOpponent", new object[] {
                        roomid,
                        username}, this.WaitingForOpponentOperationCompleted, userState);
        }
        
        private void OnWaitingForOpponentOperationCompleted(object arg) {
            if ((this.WaitingForOpponentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WaitingForOpponentCompleted(this, new WaitingForOpponentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckGameOver", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckGameOver(int roomIndex, string username, out bool win) {
            object[] results = this.Invoke("CheckGameOver", new object[] {
                        roomIndex,
                        username});
            win = ((bool)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckGameOverAsync(int roomIndex, string username) {
            this.CheckGameOverAsync(roomIndex, username, null);
        }
        
        /// <remarks/>
        public void CheckGameOverAsync(int roomIndex, string username, object userState) {
            if ((this.CheckGameOverOperationCompleted == null)) {
                this.CheckGameOverOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckGameOverOperationCompleted);
            }
            this.InvokeAsync("CheckGameOver", new object[] {
                        roomIndex,
                        username}, this.CheckGameOverOperationCompleted, userState);
        }
        
        private void OnCheckGameOverOperationCompleted(object arg) {
            if ((this.CheckGameOverCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckGameOverCompleted(this, new CheckGameOverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Room {
        
        private bool gameStartedField;
        
        private bool gameOverField;
        
        private bool hasMachineField;
        
        private string nameField;
        
        /// <remarks/>
        public bool GameStarted {
            get {
                return this.gameStartedField;
            }
            set {
                this.gameStartedField = value;
            }
        }
        
        /// <remarks/>
        public bool GameOver {
            get {
                return this.gameOverField;
            }
            set {
                this.gameOverField = value;
            }
        }
        
        /// <remarks/>
        public bool HasMachine {
            get {
                return this.hasMachineField;
            }
            set {
                this.hasMachineField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRoomListCompletedEventHandler(object sender, GetRoomListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoomListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoomListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Room[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Room[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateRoomCompletedEventHandler(object sender, CreateRoomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateRoomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateRoomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int roomIndex {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void JoinRoomCompletedEventHandler(object sender, JoinRoomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JoinRoomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JoinRoomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LeaveRoomCompletedEventHandler(object sender, LeaveRoomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LeaveRoomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LeaveRoomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int roomid {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MoveCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void WaitingForOpponentCompletedEventHandler(object sender, WaitingForOpponentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WaitingForOpponentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WaitingForOpponentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckGameOverCompletedEventHandler(object sender, CheckGameOverCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckGameOverCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckGameOverCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool win {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591